### ISSUE TITLE
Build error after uninstalling the package

### ISSUE THREAD

**Issue by azizbecha** [sam3d/next-plugin-websocket#10]
Hello, I found this package in a GitHub discussion while trying to find a solution to the problem in my Next.js app and I installed it and it worked perfectly but I realized that it does not match my case. 

Anyway, when I uninstalled it from my terminal using `npm uninstall next-plugin-websocket` and pushed my code to GitHub, deployed to Vercel. I faced the following error when building project:

![image](https://github.com/sam3d/next-plugin-websocket/assets/63454940/9038c8cc-9324-4a23-a78e-bfd5572fd882)

This error happened because the library works by injecting a couple of micro-patches into the Next.js core and this causes error when deleting the package so please take a look and think how find a solution for this issue.

Thanks for your time and efforts.

**Comment by brhx** [comment]
Hiya! Sorry to hear about these issues. Please try clearing the Vercel build cache and re-deploy? That should force a re-download of an unmodified version of Next.js.

https://vercel.com/docs/concepts/deployments/troubleshoot-a-build
