### ISSUE TITLE
run next dev found some error

### ISSUE THREAD

**Issue by zackshen** [sam3d/next-plugin-websocket#4]
hi sam3d, 

nice job! the way use websocket is very clean and easy. today i tried this plugin , but found a error in the output log. 

`this.ensureApiPage` is not a function!

can you give a full example ?  thank u

env

```
{
  "name": "ws-demo",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "13.2.4",
    "next-plugin-websocket": "^0.1.2",
    "react": "18.2.0",
    "react-dom": "18.2.0"
  }
}
```

node = 16.13.2

> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
ready - loaded websocket plugin successfully
event - compiled client and server successfully in 612 ms (168 modules)
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 146 ms (169 modules)
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
wait  - compiling / (client and server)...
event - compiled client and server successfully in 206 ms (213 modules)
error - unhandledRejection: TypeError: this.ensureApiPage is not a function

```

**Comment by zackshen** [comment]
I found that must use `next@13.1.6` can work correctly.

**Comment by yoieh** [comment]
looks like `ensureApiPage` was removed in v13.1.7-cannary.14

https://github.com/vercel/next.js/pull/45716/files#diff-2f6fd5a9538abfaf3d5b76a82a8d1ffa029f84a36f0cdae5460520c5cfc2db6bL1402
